apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/my-project3333-1533742417163/notifications/production
          name: notifications
          env:
            - name: PORT
              value: '3001'
            - name: SMTP_HOST
              value: sandbox.smtp.mailtrap.io
            - name: SMTP_PORT
              value: '2525'
            - name: SMTP_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: mailtrap-smtp-credentials
                  key: smtpUser
            - name: SMTP_AUTH_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailtrap-smtp-credentials
                  key: smtpPassword
            - name: SMTP_USER
              value: 'hello@sleepr.com'
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: '500m'
              memory: '256Mi'
            limits:
              cpu: '1'
              memory: '512Mi'
