services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/DockerFile
      target: development
    restart: unless-stopped
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229' #for debugging
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_module
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/DockerFile
      target: development
    restart: unless-stopped
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app:cached
        - /usr/src/app/node_module
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/DockerFile
      target: development
    restart: unless-stopped
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app:cached
        - /usr/src/app/node_module
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/DockerFile
      target: development
    restart: unless-stopped
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app:cached
        - /usr/src/app/node_module
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - 3306:3306
