services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/DockerFile
      target: development
    restart: unless-stopped
    command: sh -c "pnpm prisma migrate dev --schema apps/reservations/prisma/schema.prisma && pnpm prisma generate --schema apps/reservations/prisma/schema.prisma && pnpm run start:dev reservations"
    depends_on:
      - postgres
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229' #for debugging
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_module
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/DockerFile
      target: development
    restart: unless-stopped
    command: sh -c "pnpm prisma migrate dev --schema apps/auth/prisma/schema.prisma && pnpm prisma generate --schema apps/auth/prisma/schema.prisma && pnpm run start:dev auth"
    depends_on:
      - postgres
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app:cached
        - /usr/src/app/node_module
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/DockerFile
      target: development
    restart: unless-stopped
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app:cached
        - /usr/src/app/node_module
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/DockerFile
      target: development
    restart: unless-stopped
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app:cached
        - /usr/src/app/node_module
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
