apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  strategy: {}
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/my-project3333-1533742417163/payments/production
          name: payments
          env:
            - name: HTTP_PORT
              value: '3000'
            - name: NOTIFICATIONS_HOST
              value: notifications
            - name: NOTIFICATIONS_PORT
              value: '3001'
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiKey
          ports:
            - containerPort: 3000
