apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: 897722664730.dkr.ecr.eu-north-1.amazonaws.com/reservations:latest
          name: reservations
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: '3004'
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: '3002'
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENT_PORT
              value: '3000'
          ports:
            - containerPort: 3004
          resources:
            requests:
              cpu: '500m'
              memory: '256Mi'
            limits:
              cpu: '1'
              memory: '512Mi'
